[build]
  publish = "dist"
  command = "yarn run generate && yarn run build"
  functions = "./functions"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.10"
  YARN_FLAGS = "--no-ignore-optional"